import Layout from "../components/Layout";
import {
  Paper,
  Typography,
  Box,
  Grid,
  alpha,
  Avatar,
  IconButton,
} from "@mui/material";
import {
  DownloadOutlined as DownloadIcon,
  VisibilityOutlined as ViewIcon,
} from "@mui/icons-material";
import { motion } from "framer-motion";

const reports = [
  { id: 1, name: "Q4 Financial Compliance", date: "2024-01-10", type: "PDF" },
  { id: 2, name: "Service Ingestion Metrics", date: "2024-01-12", type: "Excel" },
  { id: 3, name: "Anomaly Detection Logs", date: "2024-01-13", type: "JSON" },
];

export default function ViewerReports() {
  return (
    <Layout>
      <Box mb={4}>
        <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }}>
          <Typography variant="h3" fontWeight={800} gutterBottom>
            Reports Summary
          </Typography>
          <Typography color="text.secondary">
            Access and download high-level analytical reports generated by the platform.
          </Typography>
        </motion.div>
      </Box>

      <Grid container spacing={3}>
        {reports.map((report, idx) => (
          <Grid size={{ xs: 12, md: 4 }} item key={report.id}>
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.1 }}
            >
              <Paper
                sx={{
                  p: 3,
                  borderRadius: 4,
                  background: "rgba(15, 23, 42, 0.4)",
                  backdropFilter: "blur(10px)",
                  border: "1px solid rgba(255, 255, 255, 0.05)",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                }}
              >
                <Box display="flex" alignItems="center" gap={2}>
                  <Avatar sx={{ bgcolor: alpha("#6366F1", 0.1), color: "#6366F1" }}>
                    <DownloadIcon />
                  </Avatar>
                  <Box>
                    <Typography variant="body1" fontWeight={700}>
                      {report.name}
                    </Typography>
                    <Typography variant="caption" color="text.secondary">
                      {report.type} • {report.date}
                    </Typography>
                  </Box>
                </Box>
                <IconButton color="primary" size="small">
                  <ViewIcon />
                </IconButton>
              </Paper>
            </motion.div>
          </Grid>
        ))}
      </Grid>
    </Layout>
  );
}
